arm_unit_tests_task:

  arm_container:
    image: quay.io/fedora/fedora:37
    memory: 4G
    cpu: 2

  env:
    ARCH: aarch64
    CIRRUS_CLONE_SUBMODULES: true
    PATH: ${HOME}/bin:${HOME}/.local/bin:${PATH}
    DEPENDENCIES: autoconf automake clang curl ethtool gcc git
      glibc-langpack-en groff iproute iproute-tc iputils libcap-ng-devel
      libtool net-tools nmap-ncat openssl openssl-devel python3-devel 
      python3-pip python3-sphinx tcpdump unbound unbound-devel wget
    matrix:
      - CC: gcc
        TESTSUITE: test
        TEST_RANGE: -500
      - CC: gcc
        TESTSUITE: test
        TEST_RANGE: 501-1000
      - CC: gcc
        TESTSUITE: test
        TEST_RANGE: 1001-
      - CC: clang
        TESTSUITE: test
        TEST_RANGE: -500
      - CC: clang
        TESTSUITE: test
        TEST_RANGE: 501-1000
      - CC: clang
        TESTSUITE: test
        TEST_RANGE: 1001-

  name: ARM64 ${CC} ${TESTSUITE} ${TEST_RANGE}

  dependencies_script:
    - dnf -y update
    - dnf -y install ${DEPENDENCIES}

  prepare_script:
    - ./.ci/linux-prepare.sh

  build_script:
    - ./.ci/linux-build.sh
