name: Build and Test

on:
  push:
  pull_request:
  schedule:
    # Run Sunday at midnight
    - cron: '0 0 * * 0'

env:
  CI_IMAGE: &ci_image ghcr.io/${{ github.repository_owner }}/ovn-ci-tmp:${{ github.sha }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  prepare-container:
    # This job has the following matrix, x: Job trigger, y: Branch
    # (scheduled jobs run only on main):
    # +-------+-------------------+-------------------+
    # |       | Push/Pull request |     Scheduled     |
    # +-------+-------------------+-------------------+
    # |  main |  ghcr.io - Ubuntu | ghcr.io - Fedora  |
    # +-------+-------------------+-------------------+
    # | !main |  Builds - Ubuntu  | xxxxxxxxxxxxxxxxx |
    # +-------+-------------------+-------------------+
    defaults:
      run:
        shell: bash
    env:
      DEPENDENCIES: podman make
    name: Prepare container
    if: github.repository_owner == 'ovn-org' || github.event_name != 'schedule'
    runs-on: ubuntu-24.04
    container:
      image: ubuntu:24.04
      options: --privileged

    steps:
      - uses: actions/checkout@v6

      - name: Update APT cache
        run: apt update

      - name: Install dependencies
        run: apt install -y ${{ env.DEPENDENCIES }}

      - name: Fix /etc/hosts file
        run: |
          . .ci/linux-util.sh
          fix_etc_hosts

      - name: Log in container registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Choose image distro
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        run: |
          echo "IMAGE_DISTRO=ubuntu" >> $GITHUB_ENV

      - name: Choose image distro
        if: github.event_name == 'schedule'
        run: |
          echo "IMAGE_DISTRO=fedora" >> $GITHUB_ENV

      - name: Build container
        if: github.ref_name != 'main'
        run: make ${{ env.IMAGE_DISTRO }}
        working-directory: utilities/containers

      - name: Download container
        if: github.ref_name == 'main'
        run: podman pull ghcr.io/ovn-org/ovn-tests:${{ env.IMAGE_DISTRO }}

      - name: Tag image
        run: podman tag ovn-org/ovn-tests:${{ env.IMAGE_DISTRO }} ${{ env.CI_IMAGE }}

      - name: Export image
        run: podman push ${{ env.CI_IMAGE }}

  build-linux:
    needs: [prepare-container]
    defaults:
      run:
        shell: bash
    env:
      ARCH:        ${{ matrix.cfg.arch }}
      CC:          ${{ matrix.cfg.compiler }}
      DPDK:        ${{ matrix.cfg.dpdk }}
      LIBS:        ${{ matrix.cfg.libs }}
      OPTS:        ${{ matrix.cfg.opts }}
      TESTSUITE:   ${{ matrix.cfg.testsuite }}
      TEST_RANGE:  ${{ matrix.cfg.test_range }}
      SANITIZERS:  ${{ matrix.cfg.sanitizers }}
      UNSTABLE:    ${{ matrix.cfg.unstable }}
      DEPENDENCIES: build-essential git podman

    name: linux ${{ join(matrix.cfg.*, ' ') }}
    runs-on: ubuntu-24.04
    container:
      image: *ci_image
      options: --privileged --init

    strategy:
      fail-fast: false
      matrix:
        cfg:
        - { compiler: gcc, opts: --disable-ssl }
        - { compiler: clang, opts: --disable-ssl }
        - { compiler: gcc, testsuite: dist-test }
        - { compiler: gcc, testsuite: test, test_range: "-300" }
        - { compiler: gcc, testsuite: test, test_range: "301-600" }
        - { compiler: gcc, testsuite: test, test_range: "601-", unstable: unstable }
        - { compiler: clang, testsuite: test, sanitizers: sanitizers, test_range: "-300" }
        - { compiler: clang, testsuite: test, sanitizers: sanitizers, test_range: "301-600" }
        - { compiler: clang, testsuite: test, sanitizers: sanitizers, test_range: "601-", unstable: unstable }
        - { compiler: gcc, testsuite: test, libs: -ljemalloc, test_range: "-300" }
        - { compiler: gcc, testsuite: test, libs: -ljemalloc, test_range: "301-600" }
        - { compiler: gcc, testsuite: test, libs: -ljemalloc, test_range: "601-", unstable: unstable }
        - { compiler: gcc, testsuite: system-test-dpdk, dpdk: dpdk, test_range: "-100" }
        - { compiler: gcc, testsuite: system-test-dpdk, dpdk: dpdk, test_range: "101-200" }
        - { compiler: gcc, testsuite: system-test-dpdk, dpdk: dpdk, test_range: "201-", unstable: unstable }
        - { compiler: gcc, testsuite: system-test-userspace, test_range: "-100" }
        - { compiler: gcc, testsuite: system-test-userspace, test_range: "101-200" }
        - { compiler: gcc, testsuite: system-test-userspace, test_range: "201-", unstable: unstable }
        - { compiler: gcc, testsuite: system-test, test_range: "-100" }
        - { compiler: gcc, testsuite: system-test, test_range: "101-200" }
        - { compiler: gcc, testsuite: system-test, test_range: "201-", unstable: unstable }
        - { compiler: clang, testsuite: system-test, sanitizers: sanitizers, test_range: "-100" }
        - { compiler: clang, testsuite: system-test, sanitizers: sanitizers, test_range: "101-200" }
        - { compiler: clang, testsuite: system-test, sanitizers: sanitizers, test_range: "201-", unstable: unstable }
        - { arch: x86, compiler: gcc, opts: --disable-ssl }

    steps:
    - name: Update APT cache
      run: apt update

    - name: Install dependencies
      run: apt install -y ${{ env.DEPENDENCIES }}

    - name: system-level-dependencies
      if: ${{ startsWith(matrix.cfg.testsuite, 'system-test') }}
      run: |
        apt update
        apt -y install linux-modules-extra-$(uname -r)

    - name: checkout
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      uses: actions/checkout@v6
      with:
        submodules: recursive

    # For weekly runs, don't update submodules
    - name: checkout without submodule
      if: github.event_name == 'schedule'
      uses: actions/checkout@v6

    # Weekly runs test using the tip of the most recent stable OVS branch
    # instead of the submodule.
    - name: checkout OVS
      if: github.event_name == 'schedule'
      uses: actions/checkout@v6
      with:
        repository: 'openvswitch/ovs'
        fetch-depth: 0
        path: 'ovs'

    - name: checkout OVS most recent stable branch.
      if: github.event_name == 'schedule'
      run: |
        git checkout \
          $(git branch -a -l '*branch-*' | sed 's/remotes\/origin\///' | \
            sort -V | tail -1)
      working-directory: ovs

    - name: Fix /etc/hosts file
      run: |
        . .ci/linux-util.sh
        fix_etc_hosts

    - name: Trust git repo
      run: git config --global --add safe.directory $(pwd)

    - name: Setup hugepages
      if: matrix.cfg.dpdk == 'dpdk'
      run: |
        echo 2048 > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
        mkdir /dev/hugepages
        mount -t hugetlbfs none /dev/hugepages

    - name: build and test
      run: |
        ARCH=$ARCH CC=$CC LIBS=$LIBS OPTS=$OPTS TESTSUITE=$TESTSUITE \
           TEST_RANGE=$TEST_RANGE SANITIZERS=$SANITIZERS DPDK=$DPDK \
           RECHECK=$RECHECK UNSTABLE=$UNSTABLE TIMEOUT=2h \
           BASE_VERSION=$BASE_VERSION ./.ci/linux-build.sh

    - name: collect logs on failure
      if: failure() || cancelled()
      run: |
        mkdir -p /tmp/logcollector
        cp config.log /tmp/logcollector
        cp -r tests/testsuite.* /tmp/logcollector || true
        cp -r tests/system-*-testsuite.* /tmp/logcollector || true
        cp -r tests/upgrade-testsuite.* /tmp/logcollector || true
        tar -czf /tmp/logs.tgz /tmp/logcollector

    - name: upload logs on failure
      if: failure() || cancelled()
      uses: actions/upload-artifact@v7
      with:
        name: logs-linux-${{ join(matrix.cfg.*, '-') }}
        path: /tmp/logs.tgz

  cleanup:
    needs: [build-linux]
    name: Cleanup
    if: always()
    runs-on: ubuntu-24.04
    container:
      image: ubuntu:24.04
    permissions:
      packages: write

    steps:
      - name: Update APT cache
        run: apt update

      - name: Install dependencies
        run: apt install -y curl jq

      - name: delete temporary image
        run: |
          if [ "${{ github.event.repository.owner.type }}" = "Organization" ]; then
            TYPE="orgs"
          else
            TYPE="users"
          fi
          PACKAGE_URL="https://api.github.com/${TYPE}/${{ github.repository_owner }}/packages/container/ovn-ci-tmp"
          PACKAGE_VERSION_URL="${PACKAGE_URL}/versions"
          VERSION_ID=$(curl -s \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            "$PACKAGE_VERSION_URL" | jq -r '.[] | select(.metadata.container.tags[] == "${{ github.sha }}") | .id')
          if [ -n "$VERSION_ID" ]; then
            if curl --fail-with-body -s -X DELETE \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github+json" \
              "$PACKAGE_VERSION_URL/$VERSION_ID"; then
                echo "Package version deleted successfully"
            else
                echo "Package version seems to be the last one. Attempting to delete the whole package"
                curl --fail-with-body -s -X DELETE \
                  -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                  -H "Accept: application/vnd.github+json" \
                  "$PACKAGE_URL"
            fi
          fi

  build-osx:
    env:
      CC:    clang
      OPTS:  --disable-ssl

    name:    osx clang --disable-ssl
    if: github.repository_owner == 'ovn-org' || github.event_name != 'schedule'
    runs-on: macos-latest

    strategy:
      fail-fast: false

    steps:
    - name: checkout
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      uses: actions/checkout@v6
      with:
        submodules: recursive
    # For weekly runs, don't update submodules
    - name: checkout without submodule
      if: github.event_name == 'schedule'
      uses: actions/checkout@v6
    # Weekly runs test using the tip of the most recent stable OVS branch
    # instead of the submodule.
    - name: checkout OVS
      if: github.event_name == 'schedule'
      uses: actions/checkout@v6
      with:
        repository: 'openvswitch/ovs'
        fetch-depth: 0
        path: 'ovs'
    - name: checkout OVS most recent stable branch.
      if: github.event_name == 'schedule'
      run: |
        git checkout \
          $(git branch -a -l '*branch-*' | sed 's/remotes\/origin\///' | \
            sort -V | tail -1)
      working-directory: ovs
    - name: install dependencies
      run:  brew install automake libtool
    - name: update PATH
      run:  |
        echo "$HOME/bin"        >> $GITHUB_PATH
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: set up python
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'
    - name: prepare
      run:  ./.ci/osx-prepare.sh
    - name: build
      run:  ./.ci/osx-build.sh
    - name: upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v7
      with:
        name: logs-osx-clang---disable-ssl
        path: config.log

  build-linux-rpm:
    name: linux rpm fedora
    if: github.repository_owner == 'ovn-org' || github.event_name != 'schedule'
    runs-on: ubuntu-24.04
    container: fedora:42
    timeout-minutes: 30

    strategy:
      fail-fast: false

    steps:
      - name: install dependencies
        run: dnf install -y dnf-plugins-core git rpm-build

      - name: checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: install build dependencies
        run: |
          sed -e 's/@VERSION@/0.0.1/' rhel/ovn-fedora.spec.in \
          > /tmp/ovn.spec
          dnf builddep -y /tmp/ovn.spec

      - name: Fix /etc/hosts file
        run: |
          . .ci/linux-util.sh
          fix_etc_hosts

      - name: configure OvS
        run: ./boot.sh && ./configure
        working-directory: ovs

      - name: make dist OvS
        run: make dist
        working-directory: ovs

      - name: configure OVN
        run:  ./boot.sh && ./configure

      - name: make dist OVN
        run: make dist

      - name: build RPM
        run:  make rpm-fedora

      - name: upload rpm packages
        uses: actions/upload-artifact@v7
        with:
          name: rpm-packages
          path: |
            rpm/rpmbuild/SRPMS/*.rpm
            rpm/rpmbuild/RPMS/*/*.rpm
          retention-days: 14
